---
title: "Fill in missing CHILD covariates  with mean"
author: "SL"
date: "2020-11-04"
output: html_document
---

*Purpose*: The purpose of this script is to "impute" missing covariates by filling in with the mean. 

Load required libraries.
```{r libraries}
library(tidyverse)
library(here)
```

Load covariate data
```{r covariates}
load(file=here("output_data", "covariates", "2020-11-03_CHILD_all_covariates.Rdata"))
```


Fill in covariate data with mean
```{r mean}
#create new dataframe for missing indices that are filled in with means
covariates_nameans <- covariates

#maternal perceived stress
covariates_nameans$pss_18wk <- covariates_nameans$pss_18wk %>% replace_na(mean(na.omit(covariates_nameans$pss_18wk)))
covariates_nameans$pss_36wk <- covariates_nameans$pss_36wk %>% replace_na(mean(na.omit(covariates_nameans$pss_36wk)))
covariates_nameans$pss_6mos <- covariates_nameans$pss_6mos %>% replace_na(mean(na.omit(covariates_nameans$pss_6mos)))
covariates_nameans$pss_12mos <- covariates_nameans$pss_12mos %>% replace_na(mean(na.omit(covariates_nameans$pss_12mos)))

#maternal depression (CSED)
covariates_nameans$csed_18wk <- covariates_nameans$csed_18wk %>% replace_na(mean(na.omit(covariates_nameans$csed_18wk)))
covariates_nameans$csed_36wk <- covariates_nameans$csed_36wk %>% replace_na(mean(na.omit(covariates_nameans$csed_36wk)))
covariates_nameans$csed_6mos <- covariates_nameans$csed_6mos %>% replace_na(mean(na.omit(covariates_nameans$csed_6mos)))
covariates_nameans$csed_12mos <- covariates_nameans$csed_12mos %>% replace_na(mean(na.omit(covariates_nameans$csed_12mos)))

#maternal education length
covariates_nameans$maternal_education_length <- covariates_nameans$maternal_education_length %>% replace_na(mean(na.omit(covariates_nameans$maternal_education_length)))

#paternal education length
covariates_nameans$paternal_education_length <- covariates_nameans$paternal_education_length %>% replace_na(mean(na.omit(covariates_nameans$paternal_education_length)))

#ses community rank
covariates_nameans$ses_community_rank <- covariates_nameans$ses_community_rank %>% replace_na(mean(na.omit(covariates_nameans$ses_community_rank)))

#ses canada rank
covariates_nameans$ses_canada_rank <- covariates_nameans$ses_canada_rank %>% replace_na(mean(na.omit(covariates_nameans$ses_canada_rank)))

```


save mean data set
```{r save}
save(covariates_nameans, file=here("output_data","covariates", "2020-11-12_CHILD_covariates_na_with_means.Rdata"))
```