---
title: "Fill in missing CHILD covariates  with mean"
author: "SL"
date: "2020-11-04"
output: html_document
---

*Purpose*: The purpose of this script is to "impute" missing covariates by filling in with the mean. 

Load required libraries.
```{r libraries}
library(tidyverse)
library(here)
```

Load covariate data
```{r covariates}
load(here("output_data", 
          "covariates", 
          "2022-09-27_CHILD_all_covariates.Rdata"))
```


Fill in covariate data with mean
```{r mean}
#create new dataframe for missing indices that are filled in with means
covariates_nameans <- covariates

#maternal perceived stress
pss_18wk_mean <- covariates_nameans$pss_pre18wk %>%
  na.omit() %>%
  mean() %>% 
  round()

covariates_nameans$pss_pre18wk <- covariates_nameans$pss_pre18wk %>% 
  replace_na(pss_18wk_mean)

pss_36wk_mean <- covariates_nameans$pss_pre36wk %>%
  na.omit() %>%
  mean() %>% 
  round()

covariates_nameans$pss_pre36wk <- covariates_nameans$pss_pre36wk %>% 
  replace_na(pss_36wk_mean)

pss_6mos_mean <- covariates_nameans$pss_6m %>%
  na.omit() %>%
  mean() %>% 
  round()

covariates_nameans$pss_6m <- covariates_nameans$pss_6m %>% 
  replace_na(pss_6mos_mean)

pss_12mos_mean <- covariates_nameans$pss_12m %>%
  na.omit() %>%
  mean() %>% 
  round()

covariates_nameans$pss_12m <- covariates_nameans$pss_12m %>% 
  replace_na(pss_12mos_mean)

#maternal depression (CSED)
csed_18wk_mean <- covariates_nameans$csed_pre18wk %>%
  na.omit() %>%
  mean() %>% 
  round()

covariates_nameans$csed_pre18wk <- covariates_nameans$csed_pre18wk %>% 
  replace_na(csed_18wk_mean)

csed_36wk_mean <- covariates_nameans$csed_pre36wk %>%
  na.omit() %>%
  mean() %>% 
  round()

covariates_nameans$csed_pre36wk <- covariates_nameans$csed_pre36wk %>% 
  replace_na(csed_36wk_mean)

csed_6mos_mean <- covariates_nameans$csed_6m %>%
  na.omit() %>%
  mean() %>% 
  round()

covariates_nameans$csed_6m <- covariates_nameans$csed_6m %>% 
  replace_na(csed_6mos_mean)

csed_12mos_mean <- covariates_nameans$csed_12m %>%
  na.omit() %>%
  mean() %>% 
  round()

covariates_nameans$csed_12m <- covariates_nameans$csed_12m %>% 
  replace_na(csed_12mos_mean)

#maternal education length

maternal_education_length_mean <- 
  covariates_nameans$maternal_education_length %>%
  na.omit() %>%
  mean() %>% 
  round()

covariates_nameans$maternal_education_length <- 
  covariates_nameans$maternal_education_length %>% 
  replace_na(maternal_education_length_mean)

#paternal education length
paternal_education_length_mean <- 
  covariates_nameans$paternal_education_length %>%
  na.omit() %>%
  mean() %>% 
  round()

covariates_nameans$paternal_education_length <- 
  covariates_nameans$paternal_education_length %>% 
  replace_na(paternal_education_length_mean)

#ses community rank
ses_community_rank_mean <- 
  covariates_nameans$ses_community_rank %>%
  na.omit() %>%
  mean() %>% 
  round()

#ses canada rank
covariates_nameans$ses_canada_rank <- covariates_nameans$ses_canada_rank %>% 
  replace_na(ses_community_rank_mean)

```


save mean data set
```{r save}
save(covariates_nameans, 
     file=here("output_data",
               "covariates", 
               "2022-09-27_CHILD_covariates_na_with_means.Rdata"))
```